version: "3"

services:
  todofront:
    depends_on:
      - todoback
    build: ./todo-app/front-end
    ports:
      - 3000:3000
  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
